### ISSUE TITLE
CORS error with self-signed certificates

### ISSUE THREAD

**Issue by scottbarnesg** [scottbarnesg/smart-sec-cam#14]
Some browsers like Firefox don't like cross-origin requests to URLs using self-signed certs even if you've already trusted certificate on the UI. 

Workaround:

In the browser you're using, load an API endpoint (something like https://<your-server>:8444/rooms) and go through the "this certificate can't be trusted" warning. Then, go back to the UI and refresh the page and see if its fixed.

**Comment by scottbarnesg** [comment]
Possible fix: Put everything behind a proxy. Previously tried this with nginx and it broke SocketIO connection, but may be worth another try

**Comment by CryptoJanne** [comment]
Cannot get it to work in firefox, but was able to get it working in chrome with your tip to go to a API endpoint first. Also worked in Brave browser by doing the same as in chrome.

**Comment by scottbarnesg** [comment]
Thanks for the update @CryptoJanne ! I have a work-in-progress fix for this that will serve the web app from the Flask API. I still need to do some more testing, but I think this will fix the issue in all browsers.

**Comment by scottbarnesg** [comment]
@CryptoJanne I have a testable branch [here](https://github.com/scottbarnesg/smart-sec-cam/pull/16) that you can try. Now, both the UI and API will be served over port 8443

**Comment by scottbarnesg** [comment]
Merged the fix for this, which I tested and verified works for Firefox: https://github.com/scottbarnesg/smart-sec-cam/pull/16
