### ISSUE TITLE
Push docker images to public repo

### ISSUE THREAD

**Issue by scottbarnesg** [scottbarnesg/smart-sec-cam#3]

**Comment by khlam** [comment]
Hi, stream-of-consciousness writing, hope this makes sense and saves you some time. I use an actions template to push public docker images to github packages which I think is what you're looking to do.

Quickly wrote this example to illustrate a partial idea, didn't test.

- https://github.com/khlam/smart-sec-cam/blob/ghcr/backend/.github/workflows/publish.yml

Implementation depends on how you want to organize your project, and I don't know if github actions is flexible enough to support multiple .github/workflows placed in each directory as done above. 
If it doesn't support that directory organization then one other option might be moving `.github/workflows/` into the project root dir and make a `publish.yml` for each image.

**Comment by scottbarnesg** [comment]
This is fantastic, thank you! I'm used to working with Gitlab-CI so I'm learning how Github Workflows works.

Are you interested in flushing out this out for all the container images? If so I'd be happy to accept a PR for this. We wouldn't need anything crazy to start out, just pushing to the `latest` tag for each service (redis, server, motion-detection, and frontend) when something gets merged into `master`. 

If not, no worries - I'm happy to take your example and run with it.
