### ISSUE TITLE
Run one system

### ISSUE THREAD

**Issue by neu-ma-tic** [scottbarnesg/smart-sec-cam#31]
Can this be ran on all on one system with just a usb camera plugged in, and being able to serve the web user interface to localhost? Also, if so, would it all be in one container, or multiple? Thanks

**Comment by scottbarnesg** [comment]
Yes, the system can be all on one host. For example, if you wanted to run on a system with the hostname `my-host`, you should

- Follow [the instructions for installing the server](https://github.com/scottbarnesg/smart-sec-cam#setting-up-the-server) on your system. You should then use `my-host` in place of `<server-hostname>`.
- Follow [the instructions for adding a camera](https://github.com/scottbarnesg/smart-sec-cam#adding-a-camera) on your system. You should update the value following `--server_url` to `localhost`.

Then, you should be able to access the web UI at https://my-host:8443, and the camera feed should show up automatically

**Comment by scottbarnesg** [comment]
@neu-ma-tic were you able to get this working?
